- hosts: localhost
  connection: local
  tasks:
    - name: include variables (free-form)
      include_vars: vars.yml
      no_log: 'yes'
      tags: "vars"

    - name: Create Static Address Groups on PAN FW
      panos_sag:
        ip_address: "{{ mgmt_ip }}"
        password: "{{ admin_password }}"
        sag_name: "{{ sag_name }}"
        sag_match_filter: "{{ sag_match_filter }}"
        description: 'This is a test address group'
        tags: ['test-tag',]
        operation: 'add'

    - name: Delete Static Address Groups on PAN FW
      panos_sag:
        ip_address: "{{ mgmt_ip }}"
        password: "{{ admin_password }}"
        sag_name: "{{ sag_name }}"
        description: 'This is a test address group'
        operation: 'delete'
