- hosts: localhost
  connection: local
  tasks:
    - name: import configuration file into PAN-OS
      panos_import:
        ip_address: "10.5.172.91"
        username: "admin"
        password: "paloalto"
        file: "/Users/ibojer/SourceCode/ansible-pan/samples/running-config_sample.xml"
        category: "configuration"
