- hosts: localhost
  connection: local
  tasks:
    - name: configure ethernet1/3
      panos_interface:
        password: "paloalto"
        ip_address: "10.5.172.91"
        if_name: "ethernet1/3"
        zone_name: "tap_zone"
        create_default_route: "yes"
        commit: False
