- hosts: localhost
  connection: local
  tasks:
    - name: set admin password
      panos_admin:
        ip_address: "52.33.20.80"
        password: "paloalto"
        admin_username: admin
        admin_password: "paloalto"
        commit: False
