- hosts: localhost
  connection: local

  tasks:
    - name: include variables (free-form)
      include_vars: vars.yml
      no_log: 'yes'
      tags: "vars"

    - name: Create the tags to map IP addresses
      panos_dag_tags:
        ip_address: "{{ mgmt_ip }}"
        password: "{{ admin_password }}"
        ip_to_register: "{{ ip_to_register }}"
        tag_names: "{{ tag_names }}"
        description: "Tags to allow certain IP's to access various SaaS Applications"
        operation: 'add'
      tags: "add-dagip"

    - name: List the IP address to tag mapping
      panos_dag_tags:
        ip_address: "{{ mgmt_ip }}"
        password: "{{ admin_password }}"
        tag_names: "{{ tag_names }}"
        description: "List the IP address to tag mapping"
        operation: 'list'
      tags: "list-dagip"

    - name: Unregister an IP address from a tag mapping
      panos_dag_tags:
        ip_address: "{{ mgmt_ip }}"
        password: "{{ admin_password }}"
        ip_to_register: "{{ ip_to_register }}"
        tag_names: "{{ tag_names }}"
        description: "Unregister IP address from tag mappings"
        operation: 'delete'
      tags: "delete-dagip"

    - name: Create dynamic address groups on PAN FW 
      panos_dag:
        ip_address: "{{ mgmt_ip }}"
        password: "{{ admin_password }}"
        dag_name: "{{ dag_name }}"
        dag_match_filter: "{{ dag_match_filter }}"
        description: 'Add / create dynamic address group to allow access to SaaS Applications'
        operation: 'add'
      tags: "create-dag"

    - name: List all dynamic address groups configured on the PAN FW
      panos_dag:
        ip_address: "{{ mgmt_ip }}"
        password: "{{ admin_password }}"
        dag_name: "{{ dag_name }}"
        description: 'List Dynamic Address Groups from the PAN FW'
        operation: 'list'
      tags: "list-dag"

    - name: Delete a dynamic address group on the PAN FW
      panos_dag:
        ip_address: "{{ mgmt_ip }}"
        password: "{{ admin_password }}"
        dag_name: "{{ dag_name }}"
        description: 'This is used to delete Dynamic Address Groups from the PAN FW'
        operation: 'delete'
      tags: "delete-dag"