- hosts: localhost
  connection: local
  tasks:
    # permit ssh to 1.1.1.1 using panorama and pushing the configuration to firewalls
    # that are defined in 'DeviceGroupA' device group
    - name: permit ssh to 1.1.1.1 through Panorama
      panos_security_policy:
        ip_address: '10.5.172.92'
        password: 'paloalto'
        rule_name: 'SSH permit'
        description: 'SSH rule test'
        from_zone: ['public']
        to_zone: ['private']
        source: ['any']
        source_user: ['any']
        destination: ['1.1.1.1']
        category: ['any']
        application: ['ssh']
        service: ['application-default']
        hip_profiles: ['any']
        action: 'allow'
        devicegroup: 'DeviceGroupA'
