- hosts: localhost
  connection: local
  tasks:
    - name: setup security profile group
      panos_vulnprofile:
        ip_address: "10.5.172.91"
        password: "paloalto"
        vulnprofile_name: "SampleVRule"
        description: "some description"
        rule_tuples: [{'rule_name': 'simple-client-critical', 'threat_name': 'any', 'vendor_id': 'any', 'cve': '1.1.1.1', 'host_type': 'client', 'severity': 'critical', 'action': 'default', 'capture': 'disable'}, {'rule_name': 'simple-client-high', 'threat_name': 'any', 'cve': 'any', 'vendor_id': '1.1.1.1', 'host_type': 'client', 'severity': 'high', 'action': 'default', 'capture': 'disable'}]
        exception_ids: ["42000","43000"]
        commit: False
