- hosts: localhost
  connection: local
  tasks:
    - name: create IP-Range Object
      panos_address:
        ip_address: "10.5.172.91"
        password: 'paloalto'
        type: 'ip-range'
        address_name: 'apple-range'
        address: '17.0.0.0-17.255.255.255'
        commit: False
  
    - name: create FQDN Object
      panos_address:
        ip_address: "10.5.172.91"
        password: 'paloalto'
        type: 'fqdn'
        address_name: 'google.com'
        address: 'www.google.com'
        commit: False

    - name: create IP-Netmask Object
      panos_address:
        ip_address: "10.5.172.91"
        password: 'paloalto'
        address_name: 'google_dns'
        address: '8.8.8.8/32'
        description: 'Google DNS'
        tag: 'Outbound'
        commit: False
