- hosts: localhost
  connection: local
  tasks:
    - name: setup security profile group
      panos_pg:
        ip_address: "10.5.172.91"
        username: "admin"
        password: "paloalto"
        pg_name: "pg-custom"
        virus: "default"
        spyware: "default"
        vulnerability: "default"
        url_filtering: "default"
        wildfire: "default"
        commit: False
