- hosts: localhost
  connection: local
  tasks:
    - name: generate self signed certificate
      panos_cert_gen_ssh:
        ip_address: "10.5.172.91"
        password: "paloalto"
        cert_cn: "1.1.1.1"
        cert_friendly_name: "test123"
        signed_by: "root-ca"
