- hosts: localhost
  connection: local
  tasks:
    # permit ssh to 1.1.1.1
    - name: permit ssh to 1.1.1.1
      panos_security_policy:
        ip_address: '10.5.172.91'
        username: 'admin'
        password: 'paloalto'
        rule_name: 'SSH permit'
        description: 'SSH rule test'
        from_zone: ['public']
        to_zone: ['private']
        source: ['any']
        source_user: ['any']
        destination: ['1.1.1.1']
        category: ['any']
        application: ['ssh']
        service: ['application-default']
        hip_profiles: ['any']
        action: 'allow'
        commit: false

    # Allow HTTP multimedia only from CDNs
    - name: Allow HTTP multimedia only from CDNs
      panos_security_policy:
        ip_address: '10.5.172.91'
        username: 'admin'
        password: 'paloalto'
        rule_name: 'HTTP Multimedia'
        description: 'Allow HTTP multimedia only to host at 1.1.1.1'
        from_zone: ['public']
        to_zone: ['private']
        source: ['any']
        source_user: ['any']
        destination: ['1.1.1.1']
        category: ['content-delivery-networks']
        application: ['http-video', 'http-audio']
        service: ['service-http', 'service-https']
        hip_profiles: ['any']
        action: 'allow'
        commit: false

    # more complex fictitious rule that uses profiles
    - name: More complex fictitious rule that uses profiles
      panos_security_policy:
        ip_address: '10.5.172.91'
        username: 'admin'
        password: 'paloalto'
        rule_name: 'Allow HTTP w profile'
        log_start: false
        log_end: true
        action: 'allow'
        antivirus: 'default'
        vulnerability: 'default'
        spyware: 'default'
        url_filtering: 'default'
        wildfire_analysis: 'default'
        commit: false

    # deny all
    - name: Deny all rules used as a 'catch-all' at the end
      panos_security_policy:
        ip_address: '10.5.172.91'
        username: 'admin'
        password: 'paloalto'
        rule_name: 'DenyAll'
        log_start: true
        log_end: true
        action: 'deny'
        rule_type: 'interzone'
        commit: false