- hosts: localhost
  connection: local
  tasks:
    - name: create SSH service
      panos_service:
        ip_address: "10.5.172.91"
        password: "paloalto"
        service_name: "service-tcp-22"
        protocol: "tcp"
        port: "22"
        commit: False
