- name: Create Static Address Groups on PAN FW
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Create Static Address Groups on PAN FW
    panos_sag:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
      sag_name: "{{ sag_name }}"
      sag_match_filter: "{{ sag_match_filter }}"
      description: 'This is a test address group'
      tags: ['test-tag',]
      operation: 'add'

  - name: Delete Static Address Groups on PAN FW
    panos_sag:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
      sag_name: "{{ sag_name }}"
      description: 'This is a test address group'
      operation: 'delete'
