- name: Add some objects to Panorama
  hosts: my-panorama
  connection: local
  gather_facts: False

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'panorama-secrets.yml'
    no_log: 'yes'

  - name: Add an object to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'test-address'
      address: '192.168.100.99/24'
      address_type: 'ip-netmask'
      description: 'This is a test address object'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  - name: Add a service to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      serviceobject: 'service-xyz'
      protocol: 'tcp'
      destination_port: '8889'
      description: 'This is a test service object'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  - name: Add an address group to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressgroup: 'sinkhole servers'
      static_value: ['sinkhole-v4','sinkhole-v6']
      description: 'This is an addressgroup object'
      devicegroup: 'shared_services_11022'
      operation: 'add'

  - name: Add a tag to Panorama
    panos_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tag_name: 'TestTag'
      color: 'orange'
      description: 'This is test tag'
      devicegroup: 'shared_services_11022'
      operation: 'add'
